name: Compile Whisper-Tiny for MacOS (arm64) with Metal

on:
  workflow_dispatch:
    inputs:
      quantization:
        description: "Choose quantization for model"
        required: true
        default: "q0f32"
        type: choice
        options:
          - q0f32
          - q4f32_1

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          brew install llvm cmake git python@3.11 git-lfs
          python3.11 -m venv ./venv
          source ./venv/bin/activate
          python3.11 -m pip install --upgrade pip
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
     
      - name: Build the repository
        shell: bash
        run: |
          source ./venv/bin/activate
          mkdir build
          cd build
          cmake -DUSE_METAL=ON ..
          cmake --build . --parallel $(sysctl -n hw.ncpu)

      - name: Install TVM and the built MLC-LLM package
        run: |
          source ./venv/bin/activate
          python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly-cpu
          cd python
          pip install -e .

      - name: Download model
        run: |
          git-lfs install
          git clone --depth 1 https://huggingface.co/openai/whisper-tiny

      - name: Compile model
        run: |
          source ./venv/bin/activate
          mkdir output-${{ github.event.inputs.quantization }}
          cd output-${{ github.event.inputs.quantization }}
          mlc_llm convert_weight --model-type whisper-tiny ../whisper-tiny --quantization ${{ github.event.inputs.quantization }} --output .
          mlc_llm gen_config --model-type whisper-tiny ../whisper-tiny --quantization ${{ github.event.inputs.quantization }} --conv-template whisper-tiny --output .
          mlc_llm compile --model-type whisper-tiny . --quantization ${{ github.event.inputs.quantization }} --output ./whisper-tiny.so

      - name: Upload compiled model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: whisper-tiny-${{ github.event.inputs.quantization }}-macos
          path: output-${{ github.event.inputs.quantization }}
