name: Build whisper for macOS with Metal Backend

on:
  workflow_dispatch:
    inputs:
      quantization:
        description: "Choose quantization for model"
        required: true
        default: "q0f32"
        type: choice
        options:
          - q0f32
          - q4f32_1

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          brew install llvm cmake git python@3.11  git-lfs
          python3.11 -m venv ./venv
          source ./venv/bin/activate
          python3.11 -m pip install --upgrade pip
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

      - name: Download model
        run: |
          git-lfs install
          git clone --depth 1 https://huggingface.co/openai/whisper-tiny

      - name: TVM python pkg
        run: |
          source ./venv/bin/activate
          python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly-cpu
     
      - name: Create build directory
        shell: bash
        run: |
          source ./venv/bin/activate
          mkdir build
          cd build
          cp ../cmake/config.cmake .
          echo "set(TVM_SOURCE_DIR, $GITHUB_WORKSPACE/../tvm)" >> config.cmake
          echo "set(USE_METAL ON)" >> config.cmake
          cmake ..

      - name: Build the project
        shell: bash
        run: |
          # source $HOME/.cargo/env
          source ./venv/bin/activate
          cd build
          cmake --build .

      - name: Install mlc-llm
        run: |
          source ./venv/bin/activate
          cd python
          pip install -e .

      - uses: mxschmitt/action-tmate@v3

      - name: Compile model
        run: |
          source ./venv/bin/activate
          ./ci/models_build/whisper.sh "${{ github.event.inputs.quantization }}"  metal

      - name: Upload compiled model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-whisper-${{ github.event.inputs.quantization }}
          path: output-whisper-${{ github.event.inputs.quantization }}/
